const GraphemesByLanguage = {
    en: {
        b: ["bb"],
        bb: ["b"],
        d: ["dd", "ed"],
        dd: ["d", "ed"],
        ed: ["d", "dd", "t", "tt", "th"],
        f: ["ff", "ph", "gh", "lf", "ft", "v", "ve"],
        ff: ["f", "ph", "gh", "lf", "ft"],
        ph: ["f", "ff", "gh", "lf", "ft", "v", "ve"],
        gh: ["f", "ff", "ph", "lf", "ft", "g", "gg", "gu", "gue"],
        lf: ["f", "ff", "ph", "gh", "ft"],
        ft: ["f", "ff", "ph", "gh", "lf"],
        g: ["gg", "gh", "gu", "gue", "j", "ge", "dge", "di"],
        gg: ["g", "gh", "gu", "gue", "j", "ge", "dge", "di"],
        gu: ["g", "gg", "gh", "gue"],
        gue: ["g", "gg", "gh", "gu"],
        h: ["wh"],
        wh: ["h", "w", "u", "o"],
        j: ["ge", "g", "dge", "di", "gg", "y", "i"],
        ge: ["j", "g", "dge", "di", "gg"],
        dge: ["j", "ge", "g", "di", "gg"],
        di: ["j", "ge", "g", "dge", "gg"],
        k: ["c", "ch", "cc", "lk", "qu", "q", "ck", "x"],
        c: [
            "k",
            "ch",
            "cc",
            "lk",
            "qu",
            "q",
            "ck",
            "x",
            "s",
            "ss",
            "sc",
            "ps",
            "st",
            "ce",
            "se",
        ],
        ch: [
            "k",
            "c",
            "cc",
            "lk",
            "qu",
            "q",
            "ck",
            "x",
            "tch",
            "tu",
            "ti",
            "te",
            "sh",
            "ce",
            "s",
            "ci",
            "si",
            "sci",
        ],
        cc: ["k", "c", "ch", "lk", "qu", "q", "ck", "x"],
        lk: ["k", "c", "ch", "cc", "qu", "q", "ck", "x"],
        qu: ["k", "c", "ch", "cc", "lk", "q", "ck", "x"],
        q: ["k", "c", "ch", "cc", "lk", "qu", "ck", "x"],
        ck: ["k", "c", "ch", "cc", "lk", "qu", "q", "x"],
        x: [
            "k",
            "c",
            "ch",
            "cc",
            "lk",
            "qu",
            "q",
            "ck",
            "z",
            "zz",
            "s",
            "ss",
            "ze",
            "se",
        ],
        l: ["ll"],
        ll: ["l"],
        m: ["mm", "mb", "mn", "lm"],
        mm: ["m", "mb", "mn", "lm"],
        mb: ["m", "mm", "mn", "lm"],
        mn: ["m", "mm", "mb", "lm"],
        lm: ["m", "mm", "mb", "mn"],
        n: ["nn", "kn", "gn", "pn", "ng", "ngue"],
        nn: ["n", "kn", "gn", "pn"],
        kn: ["n", "nn", "gn", "pn"],
        gn: ["n", "nn", "kn", "pn"],
        pn: ["n", "nn", "kn", "gn"],
        p: ["pp"],
        pp: ["p"],
        r: ["rr", "wr", "rh"],
        rr: ["r", "wr", "rh"],
        wr: ["r", "rr", "rh"],
        rh: ["r", "rr", "wr"],
        s: [
            "ss",
            "c",
            "sc",
            "ps",
            "st",
            "ce",
            "se",
            "z",
            "zz",
            "x",
            "ze",
            "si",
            "sh",
            "ci",
            "ch",
            "sci",
            "ti",
        ],
        ss: ["s", "c", "sc", "ps", "st", "ce", "se", "z", "zz", "x", "ze"],
        sc: ["s", "ss", "c", "ps", "st", "ce", "se"],
        ps: ["s", "ss", "c", "sc", "st", "ce", "se"],
        st: ["s", "ss", "c", "sc", "ps", "ce", "se"],
        ce: [
            "s",
            "ss",
            "c",
            "sc",
            "ps",
            "st",
            "se",
            "sh",
            "ci",
            "si",
            "ch",
            "sci",
            "ti",
        ],
        se: ["s", "ss", "c", "sc", "ps", "st", "ce", "z", "zz", "x", "ze"],
        t: ["tt", "th", "ed"],
        tt: ["t", "th", "ed"],
        th: ["t", "tt", "ed"],
        v: ["f", "ph", "ve"],
        ve: ["v", "f", "ph"],
        w: ["wh", "u", "o"],
        u: [
            "w",
            "wh",
            "o",
            "e",
            "ea",
            "ie",
            "ai",
            "a",
            "eo",
            "ei",
            "ae",
            "i",
            "ui",
            "y",
            "oo",
            "ou",
        ],
        o: [
            "w",
            "wh",
            "u",
            "i",
            "e",
            "ui",
            "y",
            "ie",
            "oa",
            "o_e",
            "oe",
            "ow",
            "ough",
            "eau",
            "oo",
            "ew",
            "ou",
            "ue",
            "u_e",
            "oew",
        ],
        z: ["zz", "s", "ss", "x", "ze", "se", "si"],
        zz: ["z", "s", "ss", "x", "ze", "se"],
        ze: ["z", "zz", "s", "ss", "x", "se"],
        si: ["s", "z", "sh", "ce", "ci", "ch", "sci", "ti"],
        tch: ["ch", "tu", "ti", "te"],
        tu: ["ch", "tch", "ti", "te"],
        ti: ["ch", "tch", "tu", "te", "sh", "ce", "s", "ci", "si", "sci"],
        te: ["ch", "tch", "tu", "ti"],
        sh: ["ce", "s", "ci", "si", "ch", "sci", "ti"],
        ci: ["sh", "ce", "s", "si", "ch", "sci", "ti"],
        sci: ["sh", "ce", "s", "ci", "si", "ch", "ti"],
        ng: ["n", "ngue"],
        ngue: ["ng", "n"],
        y: [
            "i",
            "j",
            "e",
            "ee",
            "ea",
            "ey",
            "oe",
            "ie",
            "ei",
            "eo",
            "ay",
            "o",
            "u",
            "ui",
            "igh",
            "uy",
            "ye",
            "ai",
            "is",
            "eigh",
            "i_e",
        ],
        i: [
            "y",
            "j",
            "e",
            "ee",
            "ea",
            "ey",
            "oe",
            "ie",
            "ei",
            "eo",
            "ay",
            "o",
            "u",
            "ui",
            "igh",
            "uy",
            "ye",
            "ai",
            "is",
            "eigh",
            "i_e",
            "a",
            "er",
            "ar",
            "our",
            "ur",
        ],
        a: [
            "ai",
            "au",
            "eigh",
            "aigh",
            "ay",
            "er",
            "et",
            "ei",
            "a_e",
            "ea",
            "ey",
            "e",
            "u",
            "ie",
            "eo",
            "ae",
            "ho",
            "aw",
            "ough",
            "i",
            "ar",
            "our",
            "ur",
            "or",
            "oor",
            "ore",
            "oar",
            "augh",
        ],
        ai: [
            "a",
            "au",
            "eigh",
            "aigh",
            "ay",
            "er",
            "et",
            "ei",
            "a_e",
            "ea",
            "ey",
            "e",
            "u",
            "ie",
            "eo",
            "ae",
            "i",
            "y",
            "igh",
            "uy",
            "ye",
            "is",
            "i_e",
        ],
        au: [
            "a",
            "ai",
            "eigh",
            "aigh",
            "ay",
            "er",
            "et",
            "ei",
            "a_e",
            "ea",
            "ey",
            "ho",
            "aw",
            "ough",
            "or",
            "oor",
            "ore",
            "oar",
            "our",
            "augh",
            "ar",
        ],
        eigh: [
            "a",
            "ai",
            "aigh",
            "ay",
            "er",
            "et",
            "ei",
            "au",
            "a_e",
            "ea",
            "ey",
            "i",
            "y",
            "igh",
            "ie",
            "uy",
            "ye",
            "is",
            "i_e",
        ],
        aigh: [
            "a",
            "ai",
            "eigh",
            "ay",
            "er",
            "et",
            "ei",
            "au",
            "a_e",
            "ea",
            "ey",
        ],
        ay: [
            "a",
            "ai",
            "eigh",
            "aigh",
            "er",
            "et",
            "ei",
            "au",
            "a_e",
            "ea",
            "ey",
            "e",
            "ee",
            "y",
            "oe",
            "ie",
            "i",
            "eo",
        ],
        er: [
            "a",
            "ai",
            "eigh",
            "aigh",
            "ay",
            "et",
            "ei",
            "au",
            "a_e",
            "ea",
            "ey",
            "i",
            "ar",
            "our",
            "ur",
            "ir",
            "ear",
            "or",
            "yr",
        ],
        et: [
            "a",
            "ai",
            "eigh",
            "aigh",
            "ay",
            "er",
            "ei",
            "au",
            "a_e",
            "ea",
            "ey",
        ],
        ei: [
            "a",
            "ai",
            "eigh",
            "aigh",
            "ay",
            "er",
            "et",
            "au",
            "a_e",
            "ea",
            "ey",
            "e",
            "u",
            "ie",
            "eo",
            "ae",
            "ee",
            "y",
            "oe",
            "i",
        ],
        a_e: [
            "a",
            "ai",
            "eigh",
            "aigh",
            "ay",
            "er",
            "et",
            "ei",
            "au",
            "ea",
            "ey",
        ],
        ea: [
            "a",
            "ai",
            "eigh",
            "aigh",
            "ay",
            "er",
            "et",
            "ei",
            "au",
            "a_e",
            "ey",
            "e",
            "u",
            "ie",
            "eo",
            "ae",
            "ee",
            "y",
            "oe",
            "i",
        ],
        ey: [
            "a",
            "ai",
            "eigh",
            "aigh",
            "ay",
            "er",
            "et",
            "ei",
            "au",
            "a_e",
            "ea",
            "e",
            "ee",
            "y",
            "oe",
            "ie",
            "i",
            "eo",
        ],
        e: [
            "ea",
            "u",
            "ie",
            "ai",
            "a",
            "eo",
            "ei",
            "ae",
            "ee",
            "y",
            "ey",
            "oe",
            "i",
            "ay",
            "o",
            "ui",
        ],
        ie: [
            "e",
            "ea",
            "u",
            "ai",
            "a",
            "eo",
            "ei",
            "ae",
            "ee",
            "y",
            "ey",
            "oe",
            "i",
            "ay",
            "o",
            "ui",
            "igh",
            "uy",
            "ye",
            "is",
            "eigh",
            "i_e",
        ],
        eo: [
            "e",
            "ea",
            "u",
            "ie",
            "ai",
            "a",
            "ei",
            "ae",
            "ee",
            "y",
            "ey",
            "oe",
            "i",
            "ay",
        ],
        ae: ["e", "ea", "u", "ie", "ai", "a", "eo", "ei"],
        ee: ["e", "ea", "y", "ey", "oe", "ie", "i", "ei", "eo", "ay"],
        oe: [
            "e",
            "ee",
            "ea",
            "y",
            "ey",
            "ie",
            "i",
            "ei",
            "eo",
            "ay",
            "o",
            "oa",
            "o_e",
            "ow",
            "ough",
            "eau",
            "oo",
            "ew",
            "ue",
            "u_e",
            "ui",
            "oew",
            "ou",
        ],
        ui: [
            "i",
            "e",
            "o",
            "u",
            "y",
            "ie",
            "oo",
            "ew",
            "ue",
            "u_e",
            "oe",
            "ough",
            "oew",
            "ou",
        ],
        igh: ["i", "y", "ie", "uy", "ye", "ai", "is", "eigh", "i_e"],
        uy: ["i", "y", "igh", "ie", "ye", "ai", "is", "eigh", "i_e"],
        ye: ["i", "y", "igh", "ie", "uy", "ai", "is", "eigh", "i_e"],
        is: ["i", "y", "igh", "ie", "uy", "ye", "ai", "eigh", "i_e"],
        i_e: ["i", "y", "igh", "ie", "uy", "ye", "ai", "is", "eigh"],
        ho: ["a", "au", "aw", "ough"],
        aw: [
            "a",
            "ho",
            "au",
            "ough",
            "or",
            "oor",
            "ore",
            "oar",
            "our",
            "augh",
            "ar",
        ],
        ough: [
            "a",
            "ho",
            "au",
            "aw",
            "o",
            "oa",
            "o_e",
            "oe",
            "ow",
            "eau",
            "oo",
            "ew",
            "ue",
            "u_e",
            "ui",
            "oew",
            "ou",
            "or",
            "oor",
            "ore",
            "oar",
            "our",
            "augh",
            "ar",
        ],
        oa: ["o", "o_e", "oe", "ow", "ough", "eau", "oo", "ew"],
        o_e: ["o", "oa", "oe", "ow", "ough", "eau", "oo", "ew"],
        ow: ["o", "oa", "o_e", "oe", "ough", "eau", "oo", "ew", "ou"],
        eau: ["o", "oa", "o_e", "oe", "ow", "ough", "oo", "ew"],
        oo: [
            "o",
            "oa",
            "o_e",
            "oe",
            "ow",
            "ough",
            "eau",
            "ew",
            "u",
            "ou",
            "ue",
            "u_e",
            "ui",
            "oew",
        ],
        ew: [
            "o",
            "oa",
            "o_e",
            "oe",
            "ow",
            "ough",
            "eau",
            "oo",
            "ue",
            "u_e",
            "ui",
            "oew",
            "ou",
        ],
        ou: [
            "o",
            "oo",
            "u",
            "ew",
            "ue",
            "u_e",
            "oe",
            "ough",
            "ui",
            "oew",
            "ow",
        ],
        ue: ["o", "oo", "ew", "u_e", "oe", "ough", "ui", "oew", "ou"],
        u_e: ["o", "oo", "ew", "ue", "oe", "ough", "ui", "oew", "ou"],
        oew: ["o", "oo", "ew", "ue", "u_e", "oe", "ough", "ui", "ou"],
        oi: ["oy", "uoy"],
        oy: ["oi", "uoy"],
        uoy: ["oi", "oy"],
        ar: [
            "a",
            "er",
            "i",
            "our",
            "ur",
            "aw",
            "or",
            "oor",
            "ore",
            "oar",
            "augh",
            "ough",
            "au",
        ],
        our: [
            "a",
            "er",
            "i",
            "ar",
            "ur",
            "ir",
            "ear",
            "or",
            "yr",
            "aw",
            "oor",
            "ore",
            "oar",
            "augh",
            "ough",
            "au",
            "ure",
        ],
        ur: ["a", "er", "i", "ar", "our", "ir", "ear", "or", "yr"],
        air: ["are", "ear", "ere", "eir", "ayer"],
        are: ["air", "ear", "ere", "eir", "ayer"],
        ear: [
            "air",
            "are",
            "ere",
            "eir",
            "ayer",
            "ir",
            "er",
            "ur",
            "or",
            "our",
            "yr",
            "eer",
            "ier",
        ],
        ere: ["air", "are", "ear", "eir", "ayer", "eer", "ier"],
        eir: ["air", "are", "ear", "ere", "ayer"],
        ayer: ["air", "are", "ear", "ere", "eir"],
        ir: ["er", "ur", "ear", "or", "our", "yr"],
        or: [
            "ir",
            "er",
            "ur",
            "ear",
            "our",
            "yr",
            "aw",
            "a",
            "oor",
            "ore",
            "oar",
            "augh",
            "ar",
            "ough",
            "au",
        ],
        yr: ["ir", "er", "ur", "ear", "or", "our"],
        oor: ["aw", "a", "or", "ore", "oar", "our", "augh", "ar", "ough", "au"],
        ore: ["aw", "a", "or", "oor", "oar", "our", "augh", "ar", "ough", "au"],
        oar: ["aw", "a", "or", "oor", "ore", "our", "augh", "ar", "ough", "au"],
        augh: ["aw", "a", "or", "oor", "ore", "oar", "our", "ar", "ough", "au"],
        eer: ["ear", "ere", "ier"],
        ier: ["ear", "eer", "ere"],
        ure: ["our"],
    },
};

export default GraphemesByLanguage;
